#!/usr/bin/env python3
"""Build the public marketing pages with Python's standard library.

Run from any directory. Existing privacy pages and original branding assets are
never read, rewritten or generated by this script.
"""
import json
from html import escape as esc
from pathlib import Path
from localize_site import write_localized_versions, sitemap_entries

ROOT = Path(__file__).resolve().parents[1]
BASE = 'https://pix-kit.com'
EMAIL = 'niko@pix-kit.com'
APPS = json.loads((ROOT / 'data/apps.json').read_text())
MEDIA = json.loads((ROOT / 'data/media.json').read_text())
VERSION = '20261007-i18n'


def text(value):
    return esc(str(value), quote=True)


def play_url(app):
    return 'https://play.google.com/store/apps/details?id=' + app['package'] + '&hl=en'


def play_badge(app):
    return f'''<a class="play-link" href="{text(play_url(app))}" target="_blank" rel="noopener noreferrer" aria-label="Get {text(app['name'])} on Google Play (opens in a new tab)">
      <img src="/assets/google-play-badge.png" alt="Get it on Google Play" width="646" height="250" loading="lazy" decoding="async"></a>'''


def icon(app, eager=False):
    return f'<img class="app-icon" src="/assets/apps/{app["slug"]}/icon.webp" width="160" height="160" alt="" {"" if eager else "loading=lazy"} decoding="async">'


def app_head(app):
    return f'<div class="app-head">{icon(app)}<div><h2 data-brand-letters>{text(app["name"])}</h2><p class="category">{text(app["category"])} · Android</p></div></div>'


def gallery(app, detail=False):
    slug = app['slug']
    metadata = {item['stem']: item for item in MEDIA[slug]}
    count = len(app['captions']) + bool(app['video'])
    figures = []
    for index, (stem, caption, alt) in enumerate(app['captions']):
        item = metadata[stem]
        src = f'/assets/apps/{slug}/{stem}'
        sizes = '(max-width: 540px) 280px, (max-width: 860px) 600px, 480px' if stem == 'feature-graphic' else '(max-width: 540px) 220px, 300px'
        eager = detail and index == 0
        figures.append(f'''<figure class="slide" role="group" aria-roledescription="slide" aria-label="{index + 1} of {count}">
          <div class="slide-media"><a class="image-open" data-image href="{src}.webp" aria-label="Enlarge: {text(caption)}">
            <img src="{src}-small.webp" srcset="{src}-small.webp {item['smallWidth']}w, {src}.webp {item['width']}w" sizes="{sizes}" width="{item['width']}" height="{item['height']}" alt="{text(alt)}" loading="{'eager' if eager else 'lazy'}" decoding="async"></a></div>
          <figcaption>{text(caption)}</figcaption></figure>''')
    if app['video']:
        figures.append(f'''<figure class="slide" role="group" aria-roledescription="slide" aria-label="{count} of {count}">
          <div class="slide-media"><a class="video-preview" href="https://www.youtube.com/watch?v={app['video']}" target="_blank" rel="noopener noreferrer" aria-label="Play the official PixGraph trailer on YouTube">
            <img src="/assets/apps/{slug}/feature-graphic-small.webp" width="1024" height="500" alt="" loading="lazy" decoding="async">
            <span class="video-label"><span>▶ &nbsp; Watch the trailer</span></span></a></div>
          <figcaption>Official trailer · <a href="https://www.youtube.com/watch?v={app['video']}" target="_blank" rel="noopener noreferrer">Open on YouTube</a></figcaption></figure>''')
    return f'''<section class="gallery" data-gallery aria-roledescription="carousel" aria-label="{text(app['name'])} screenshots and media">
      <div class="gallery-track" tabindex="0" role="group" aria-label="Swipe or use the left and right arrow keys to browse {text(app['name'])} images">{''.join(figures)}</div>
      <div class="gallery-tools" hidden><span class="gallery-status" data-status role="status" aria-live="polite" aria-atomic="true">1 / {count}</span>
        <div class="gallery-buttons"><button class="gallery-button" type="button" data-previous aria-label="Previous {text(app['name'])} image">←</button><button class="gallery-button" type="button" data-next aria-label="Next {text(app['name'])} image">→</button></div></div>
      <p class="gallery-hint">Swipe to explore · Tap a screenshot to enlarge</p></section>'''


def tags(app):
    return '<ul class="tags" aria-label="Highlights">' + ''.join(f'<li>{text(tag)}</li>' for tag in app['tags']) + '</ul>'


def policy(app):
    return f'<a class="policy-link" href="/privacy/{app["slug"]}.html">Privacy Policy</a>'


def app_schema(app):
    return {
        '@type': 'SoftwareApplication', '@id': f'{BASE}/apps/{app["slug"]}/#app',
        'name': app['name'], 'url': f'{BASE}/apps/{app["slug"]}/',
        'description': app['description'], 'applicationCategory': app['schemaCategory'],
        'operatingSystem': 'Android', 'downloadUrl': play_url(app),
        'image': f'{BASE}/assets/apps/{app["slug"]}/feature-graphic.webp',
        'screenshot': [f'{BASE}/assets/apps/{app["slug"]}/{caption[0]}.webp' for caption in app['captions'][1:]],
        'publisher': {'@id': BASE + '/#organization'},
        'offers': {'@type': 'Offer', 'price': '0', 'priceCurrency': 'USD', 'url': play_url(app), 'description': 'Free download with optional in-app purchases.'}
    }


def page(path, title, description, body, section='apps', schema=None, image_url=None, noindex=False):
    canonical = BASE + path
    nav = ''.join(f'<a href="{href}"{(" aria-current=\"page\"" if section == key else "")}>{label}</a>'
                  for key, href, label in [('apps', '/', 'Apps'), ('about', '/about/', 'About us'), ('contact', '/contact/', 'Contact')])
    graph = [
        {'@type': 'Organization', '@id': BASE + '/#organization', 'name': 'Pix-kit', 'url': BASE + '/',
         'logo': BASE + '/assets/pix-kit-logo-symbol.png', 'email': EMAIL},
        {'@type': 'WebSite', '@id': BASE + '/#website', 'name': 'Pix-kit', 'url': BASE + '/', 'inLanguage': 'en', 'publisher': {'@id': BASE + '/#organization'}}
    ]
    graph.extend(schema or [])
    meta_image = image_url or BASE + '/assets/brand/social.jpg'
    html = f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{text(title)}</title>
  <meta name="description" content="{text(description)}">
  <meta name="robots" content="{'noindex, follow' if noindex else 'index, follow, max-image-preview:large'}">
  <link rel="canonical" href="{canonical}">
  <meta name="theme-color" content="#ffffff">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="Pix-kit">
  <meta property="og:locale" content="en_US">
  <meta property="og:title" content="{text(title)}">
  <meta property="og:description" content="{text(description)}">
  <meta property="og:url" content="{canonical}">
  <meta property="og:image" content="{meta_image}">
  <meta property="og:image:alt" content="{text(title)}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{text(title)}">
  <meta name="twitter:description" content="{text(description)}">
  <meta name="twitter:image" content="{meta_image}">
  <link rel="icon" type="image/png" href="/assets/pix-kit-logo-symbol.png">
  <link rel="apple-touch-icon" href="/assets/pix-kit-logo-symbol.png">
  <link rel="stylesheet" href="/assets/css/site.css?v={VERSION}">
  <!-- Optional P/K color experiment: remove the following stylesheet to disable. -->
  <link rel="stylesheet" href="/assets/css/letter-colors.css?v={VERSION}">
  <script src="/assets/js/site.js?v={VERSION}" defer></script>
  <script src="/assets/js/letter-colors.js?v={VERSION}" defer></script>
  <script type="application/ld+json">{json.dumps({'@context': 'https://schema.org', '@graph': graph}, ensure_ascii=False).replace('<', chr(92) + 'u003c')}</script>
</head>
<body>
  <a class="skip-link" href="#main">Skip to content</a>
  <header class="site-nav"><div class="wrap nav-inner">
    <a class="brand" href="/" aria-label="Pix-kit home"><img src="/assets/brand/symbol.webp" width="96" height="96" alt=""><span data-brand-letters>Pix-kit</span></a>
    <nav class="nav-links" aria-label="Main navigation">{nav}</nav>
  </div></header>
  <main id="main" class="wrap">{body}</main>
  <footer class="footer"><div class="wrap"><div class="footer-inner"><p>© 2026 Pix-kit · Build. Learn. Play.</p>
    <nav class="footer-links" aria-label="Footer"><a href="/about/">About us</a><a href="/contact/">Contact</a><a href="/privacy/pix-graph.html">PixGraph privacy</a><a href="/privacy/pix-moments.html">Pix-Moments privacy</a></nav></div>
    <p class="legal-note">Google Play and the Google Play logo are trademarks of Google LLC.</p></div></footer>
  <dialog class="lightbox" id="image-viewer" aria-label="Enlarged screenshot"><div class="lightbox-head"><p data-viewer-caption></p><button class="gallery-button" type="button" data-close aria-label="Close enlarged screenshot">×</button></div><img alt=""></dialog>
</body>
</html>
'''
    write_localized_versions(path, html)


def banner(eager=True):
    return f'<img class="banner" src="/assets/brand/banner-680.webp" srcset="/assets/brand/banner-680.webp 680w, /assets/brand/banner-1360.webp 1360w" sizes="(max-width: 720px) calc(100vw - 28px), 680px" width="1672" height="941" alt="Pix-kit — Build. Learn. Play. Blue and orange illustrations of ideas, technology and everyday projects." {"fetchpriority=high" if eager else "loading=lazy"} decoding="async">'


def home():
    cards = []
    for app in APPS:
        cards.append(f'''<article class="app-card" id="{app['slug']}">{app_head(app)}{gallery(app)}
          <div class="card-copy"><h3 data-brand-letters>{text(app['headline'])}</h3><p>{text(app['summary'])}</p>{tags(app)}
          <div class="actions">{play_badge(app)}<a class="text-link" href="/apps/{app['slug']}/">Explore {text(app['name'])} <span aria-hidden="true">→</span></a></div>{policy(app)}</div></article>''')
    body = f'''<section class="hero">{banner()}<h1 data-brand-letters>Our apps</h1><p class="lead">Recover the numbers. Remember the moments.<br>Thoughtful Android tools for the things you want to do.</p></section>
      <section class="apps" aria-label="Explore Pix-kit Android apps">{''.join(cards)}</section>
      <aside class="after-apps"><div><h2 data-brand-letters>A little curiosity goes a long way.</h2><p>From practical apps to children’s books, discover the ideas behind Pix-kit.</p></div><a class="text-link" href="/about/">Meet Pix-kit <span aria-hidden="true">→</span></a></aside>'''
    schema = [{'@type': 'CollectionPage', '@id': BASE + '/#apps', 'url': BASE + '/', 'name': 'Pix-kit Android apps', 'mainEntity': {'@type': 'ItemList', 'itemListElement': [{'@type': 'ListItem', 'position': i + 1, 'url': BASE + '/apps/' + app['slug'] + '/', 'name': app['name']} for i, app in enumerate(APPS)]}}]
    page('/', 'Pix-kit | Android Apps to Explore Data & Keep Moments', 'Discover PixGraph for chart digitization and Pix-Moments for countdowns, photo progress and widgets. Explore screenshots and get our Android apps on Google Play.', body, schema=schema)


def app_page(app):
    name = text(app['name'])
    stories = ''.join(f'<section class="story"><p class="eyebrow">{text(kicker)}</p><h2 data-brand-letters>{text(title)}</h2><p>{text(copy)}</p></section>' for kicker, title, copy in app['sections'])
    faq = ''.join(f'<details><summary>{text(question)}</summary><p>{text(answer)}</p></details>' for question, answer in app['faq'])
    title = f'{app["name"]} — ' + ('Android Chart Digitizer & Regression | Pix-kit' if app['slug'] == 'pix-graph' else 'Countdowns, Day Counters & Widgets | Pix-kit')
    body = f'''<nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Our apps</a> <span aria-hidden="true">/</span> <span aria-current="page">{name}</span></nav>
      <section class="detail-hero"><div>{icon(app, True)}<p class="eyebrow">{text(app['category'])} · Android</p><h1 data-brand-letters>{name}</h1><h2 data-brand-letters>{text(app['headline'])}</h2><p class="summary">{text(app['summary'])}</p>{tags(app)}<div class="actions">{play_badge(app)}{policy(app)}</div></div>{gallery(app, True)}</section>
      <p class="audience">{text(app['audience'])}</p><div class="story-grid">{stories}</div>
      <section class="faq"><h2 data-brand-letters>A few things to know</h2>{faq}</section>
      <section class="download-panel"><h2 data-brand-letters>Make room for {name}.</h2><p>{text(app['pricing'])}</p><div class="actions">{play_badge(app)}<a class="text-link" href="/contact/?app={app['slug']}">Questions? Get in touch <span aria-hidden="true">→</span></a></div>{policy(app)}</section>'''
    schema = [app_schema(app), {'@type': 'BreadcrumbList', 'itemListElement': [{'@type': 'ListItem', 'position': 1, 'name': 'Our apps', 'item': BASE + '/'}, {'@type': 'ListItem', 'position': 2, 'name': app['name'], 'item': BASE + '/apps/' + app['slug'] + '/'}]}]
    page('/apps/' + app['slug'] + '/', title, app['description'], body, schema=schema, image_url=f'{BASE}/assets/apps/{app["slug"]}/feature-graphic.webp')


def about():
    body = f'''<header class="page-intro"><p class="eyebrow">About Pix-kit</p><h1 data-brand-letters>Useful ideas.<br>Room to play.</h1><p class="lead">We create digital tools and books that make everyday life a little more practical, creative and curious.</p></header>
      <section class="about-layout"><div><h2 data-brand-letters>Build. Learn. Play.</h2><p>Pix-kit is a brand for digital content: Android applications, useful tools and books, including stories and learning experiences for children. Different formats, with the same starting point — an idea that helps someone do, understand or imagine something.</p><p>Sometimes that means turning a graph into usable numbers. Sometimes it means keeping a meaningful date in sight, or watching a project grow through photos. And sometimes it means giving a young reader something new to discover.</p></div><div class="about-image">{banner(False)}</div></section>
      <div class="story-grid about-values"><section class="story"><p class="eyebrow">Practical by nature</p><h2 data-brand-letters>Tools with a clear purpose.</h2><p>Our apps start with a concrete task. We focus on making that task approachable, with thoughtful controls and space for people to work in their own way.</p></section><section class="story"><p class="eyebrow">Curious at heart</p><h2 data-brand-letters>Learning can be playful.</h2><p>Books and digital experiences can open the same door: a question, an experiment, a story. We make room for discovery, especially for children finding their way through new ideas.</p></section></div>
      <aside class="after-apps"><div><h2 data-brand-letters>See what we’re building.</h2><p>Explore our Android apps today. Our books will have a place here too.</p></div><a class="text-link" href="/">Explore our apps <span aria-hidden="true">→</span></a></aside>'''
    page('/about/', 'About Pix-kit | Digital Tools, Learning & Children’s Books', 'Meet Pix-kit: a brand creating Android apps, practical digital tools and children’s books. Build, learn and play with ideas for everyday life.', body, 'about', [{'@type': 'AboutPage', 'name': 'About Pix-kit', 'url': BASE + '/about/', 'about': {'@id': BASE + '/#organization'}}])


def contact():
    body = f'''<header class="page-intro"><p class="eyebrow">Contact</p><h1 data-brand-letters>Let’s talk.</h1><p class="lead">A question about an app, an idea to share, or something that needs a closer look? We’d like to hear from you.</p></header>
      <section class="contact-email-panel"><h2 data-brand-letters>Write to us directly at</h2><a class="button email-link" href="mailto:{EMAIL}">{EMAIL}</a><p>For an app issue, your device model, Android version and app version help us understand what happened.</p></section>
      <aside class="contact-policy-panel"><h2 data-brand-letters>Looking for a policy?</h2><p>Read how each app handles your information.</p><a href="/privacy/pix-graph.html">PixGraph Privacy Policy</a> · <a href="/privacy/pix-moments.html">Pix-Moments Privacy Policy</a></aside>'''
    page('/contact/', 'Contact Pix-kit | App Support & Enquiries', 'Contact Pix-kit for PixGraph and Pix-Moments support, feedback, books and general enquiries. Send a message or email niko@pix-kit.com.', body, 'contact', [{'@type': 'ContactPage', 'name': 'Contact Pix-kit', 'url': BASE + '/contact/'}])
    page('/contact/thanks/', 'Contact Pix-kit | App Support & Enquiries', 'Contact Pix-kit for PixGraph and Pix-Moments support, feedback, books and general enquiries. Send a message or email niko@pix-kit.com.', f'<section class="simple-page"><h1 data-brand-letters>Contact</h1><p>Write to us directly at</p><a class="button" href="mailto:{EMAIL}">{EMAIL}</a></section>', 'contact', noindex=True)


def main():
    home()
    for app in APPS:
        app_page(app)
    about()
    contact()
    page('/404.html', 'Page Not Found | Pix-kit', 'Return to Pix-kit to explore our apps or get in touch.', '<section class="simple-page"><p class="eyebrow">404 · Page not found</p><h1 data-brand-letters>A small detour.</h1><p>We couldn’t find that page. Our apps and contact details are right this way.</p><a class="button" href="/">Back to our apps</a></section>', section='', noindex=True)
    urls = sitemap_entries()
    urls += ['/privacy/' + p.name for p in sorted((ROOT / 'privacy').glob('*.html'))]
    entries = ''.join(f'  <url><loc>{BASE}{path}</loc></url>\n' for path in urls)
    (ROOT / 'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + entries + '</urlset>\n')
    (ROOT / 'robots.txt').write_text(f'User-agent: *\nAllow: /\n\nSitemap: {BASE}/sitemap.xml\n')
    print('Built 133 localized pages (19 languages), sitemap.xml and robots.txt. Privacy files left unchanged.')


if __name__ == '__main__':
    main()
